# config.yml ------
#

servers:
  - server:
      scheme: http
      host: dev-apib.zozoclub.jp
      port: 80
      path: /asp/admin/AppSetter.asp
  - server:
      scheme: http
      host: dev-soso-api.zozoclub.jp
      port: 80
      path: /asp/admin/AppSetter.xxxasp
    
