# config.yml ------
#

servers:
  - server:
      scheme: http
      host: 192.168.0.1
      port: 80
      path: /asp/admin/AppSetter.asp
  - server:
      scheme: http
      host: 192.168.0.2
      port: 80
      path: /asp/admin/AppSetter.asp
    
